### ISSUE TITLE
I can't get noerr to work when the -L string does not end in %N

### ISSUE THREAD

**Issue by nrnrnr** [svnk/noerr#2]
I'm using Moscow ML with noweb with this option:  `-L(*#line %L "%F"*)`. There is no newline.  Unfortunately, noerr is not able to translate error messages.

Here is the error message:

```
File "uclu.sml", line 4201, characters 23-75:
!            | _      => eprintln ("Usage: " ^ CommandLine.name () ^ " [-q]")
!                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
! Type clash: expression of type
!   unit
! cannot have type
!   'a -> 'b
```

And here is the location in the file where the error occurs:

```
(*#line 1625 "mlscheme.nw"*)val _ = op runAs : interactivity -> unit
(*#line 1645 "mlscheme.nw"*)val _ = case CommandLine.arguments ()
          of []     => runAs INTERACTIVE
           | ["-q"] => runAs NONINTERACTIVE
           | _      => eprintln ("Usage: " ^ CommandLine.name () ^ " [-q]")
zorch
```

(The `zorch` is an error I have deliberately seeded in order to test noerr.)

I was expecting this error to be reported on line 1648 of file mlscheme.nw.

**Comment by svnk** [comment]
Can you try if d81386a8a170eedd01e8369eecd43f6e40cb1b9d fixes the issue for you?

(BTW: this LINE expression looks like ist was DESIGNED to teach me quoting in bash and perl regexes ;)
the testing command line that worked looked like this (mostly to remind me, but it DOES look ugly).

`$ cat compiler_error.txt |perl noerr.pl -L"\\(\\*#line %L \"%F\"\\*\\)"`

**Comment by nrnrnr** [comment]
Bad news:

```
noerr mosmlc -c /tmp/book/src/uclu/uclu.sml
Unknown verb pattern '#line ([0-9]+' in regex; marked by <-- HERE in m/(*#line ([0-9]+) <-- HERE  "([\w\.]+)"*)/ at noerr.nw line 543.
mk: noerr mosmlc -c /tmp/book/prototype/uclu/uclu.sml  : exit status=exit(255)
```

**Comment by nrnrnr** [comment]
I saw your mail.  If I escape the brackets and the star in my `-L` line, it works.  But surely I shouldn't have to do that, right?  I should be able to use the same string that I pass to `notangle`, shouldn't I?

I wonder if there is a Perl primitive, or a package, that converts a string to a regexp that matches only the given string?

BTW, the escapes are easier if you use the POSIX shell with single quotes:

```
  case "$cmd" in
      mosmlc) lineformat='-L\(\*#line %L "%F"\*\)' ;;
      impcore|nml|uclu|uml|uscheme|usmalltalk) lineformat='-L;;;%F:%L%N' ;;
      *) echo "No automatic line format for $cmd" >&2 ; exit 1 ;;
  esac 
```

**Comment by nrnrnr** [comment]
OK, I think I have eliminated the need to escape these metacharacters.  I am about to create another pull request.
