### ISSUE TITLE
Can error detection affect exit status?

### ISSUE THREAD

**Issue by nrnrnr** [svnk/noerr#9]
I'm using noerr.pl in a pipeline, where if it detects an error, I would like to have it exit with a nonzero status.  I am not sure if you like this as a default.  I thought about putting it in as an option, but as the text says, 

> I get just one option, so there is no need for sophistication. Maybe later.

My Perl skills are not up to revising this code.  What do you advise? Can you help?

**Comment by svnk** [comment]
I just pushed 4f64fd8937f5a24526e09996011b12ac23001512 which adds -E that exits with 1 if any errors are detected.
